Pmvhaven Scraper
stashapp/CommunityScrapers pull request #1540
Opened 2023-11-26 22:28 UTC by JackDawson94

Add a scraper for PMVHaven, a new popular hosting site for PMVs

2023-11-29 00:55 UTC, Maista6969 requested changes
This looks good, but would you mind rebasing to the master branch? We've recently restructured the repo to support the new package management features coming in stash v0.24 and all scrapers that are not simple XPath scrapers should now be placed in subfolders: you can have a look at the [IAFD scraper](https://github.com/stashapp/CommunityScrapers/tree/master/scrapers/IAFD) to get an idea of what I mean

2023-11-30 23:25 UTC, JackDawson94 commented
> This looks good, but would you mind rebasing to the master branch? We've recently restructured the repo to support the new package management features coming in stash v0.24 and all scrapers that are not simple XPath scrapers should now be placed in subfolders: you can have a look at the [IAFD scraper](https://github.com/stashapp/CommunityScrapers/tree/master/scrapers/IAFD) to get an idea of what I mean

Ok moved and fixed to work with the new structure 👍

2023-12-01 03:27 UTC, Maista6969 approved these changes

2023-12-01 03:33 UTC, Maista6969 commented
Great job, thanks for contributing 🙂

2023-12-01 03:33 UTC, merged