Update ManyVids Scraper
stashapp/CommunityScrapers pull request #1660
Opened 2024-02-19 23:46 UTC by electricfish1

Update Manyvids scrapper to support the new site layout/features. 

- JSON scrapers leveraging the new bff API
- Removes decency of Python scraper, while retaining all prior scape types:
   - performerByName
   - performerByURL
   - sceneByName
   - sceneByQueryFragment
   - sceneByURL
 - Introduces new sceneByFragment scrape type

2024-02-20 18:02 UTC, Maista6969 requested changes
This is great, one less Python scraper to worry about 🙂

I had a few nitpicks, will await your thoughts on those before I merge this

2024-02-20 18:02 UTC, Maista6969 commented on scrapers/ManyVids.yml
> +        Image: data.thumbnail
Can we use the screenshot instead here? They're the same in every case I've tested with and slightly higher resolution
```suggestion
        Image: data.screenshot
```

2024-02-22 19:48 UTC, Maista6969 approved these changes

2024-02-22 19:48 UTC, merged

2024-02-25 21:45 UTC, electricfish1 commented
> This is great, one less Python scraper to worry about 🙂
> 
> I had a few nitpicks, will await your thoughts on those before I merge this

Apologies @Maista6969, had gone AFK for a few days after opening this. Your suggestions were great!