Teamskeet API ? (Script JSON)
stashapp/CommunityScrapers pull request #362
Opened 2021-02-07 09:49 UTC by Belleyy

Copy paste my MindGeekAPI to Teamskeet.

You need the URL  (`https://www.teamskeet.com/movies/`) then choose "TeamskeetJSON"
Can maybe avoid to get blocked by Cloudflare.

Draft atm because the URL don't look like something permanent (**ts-elastic-d5cat0jl5o**)

-------

If you want to save the JSON, write - logJSON in the .yml

```yaml
sceneByFragment:
    action: script
    script:
      - python
      - MindGeekAPI.py
      - logJSON # Save the JSON from the API to a file
```

2021-02-07 11:26 UTC, bnkai commented
The `doc` approach seems safer to avoid false positives.
It might be worth it to validate the url before quering eg making sure that it has the `https://www.teamskeet.com/movies/` +`id` form.
That way we avoid spamming the api for wrong requests and we are sure that the url saved if a result is returned is ok.
I think saving to a file the json with id.json would be safe enough ( as you only look for  one site now )

2021-02-07 11:31 UTC, bnkai commented on scrapers/TeamskeetJSON.py
> +# Image can be poster or poster_fallback
leftover comment from copy/paste ?

2021-02-07 11:32 UTC, bnkai commented on scrapers/TeamskeetJSON.py
> +# Get the id and instance token
leftover comment?

2021-02-08 01:12 UTC, SpedNSFW commented
Just as a reminder, you will need to add this to the `SCRAPERS-LIST.md` with Python v3.6 or later as a requirement.

2021-02-09 11:03 UTC, bnkai commented
> Just as a reminder, you will need to add this to the `SCRAPERS-LIST.md` with Python v3.6 or later as a requirement.

As mentioned in the MindGeek api scraper  its probably better to add to a separate section and not in the SCRAPERS-LIST.
If it ends up supporting scrape by URL also then we should propably remove the old `plain` scraper and add to the list.

2021-02-16 10:30 UTC, bnkai commented
@Belleyy 
Should we use this as the default scraper for Teamskeet? The one we have now is probably useless.
You would only need to rename your yml file to match the one we have now
TeamskeetJSON.yml -> Teamskeet.yml
and use scenebyurl instead of fragment (maybe change the name to Teamskeet also)
```yaml
name: "Teamskeet"
sceneByURL:
  - url:
      - teamskeet.com/movies/
    action: script
    script:
      - python
      - TeamskeetJSON.py
      # - logJSON # Save the JSON from the API to a file
# Last Updated February 07, 2021
```

2021-02-16 13:57 UTC, Belleyy commented
> 
> 
> @Belleyy
> Should we use this as the default scraper for Teamskeet? The one we have now is probably useless.

I am for it, because i can't manage to get any scene with the Xpath, and many people seem to have the same problem...
So it's probably easier to have a working method that work for everyone (just need python with requests...) 👍

2021-02-16 23:28 UTC, SpedNSFW requested changes

2021-02-16 23:28 UTC, SpedNSFW commented on SCRAPERS-LIST.md
> +teamskeet.com|Teamskeet.yml|:heavy_check_mark:|:x:|:x:|:x:|Python (with requests)|-
```suggestion
teamskeet.com|Teamskeet.yml|:heavy_check_mark:|:x:|:x:|:x:|Python >= 3.6|-
```

Keeps it inline with the other Python scrapers.

2021-02-17 08:21 UTC, merged