Create wetandpissy.yml
stashapp/CommunityScrapers pull request #370
Opened 2021-02-17 08:50 UTC by JaseNZC

2021-02-17 09:01 UTC, SpedNSFW requested changes
File needs to be in the scrapers directory. Also can you please add it to the SCRAPERS-LIST.md file please.

2021-02-17 09:19 UTC, JaseNZC commented
Bugger sorry thought it was in the scrapers dir no idea how to move it now.
SCRAPERS-LIST.md updated and PR issued (guess I was supposed to do that)

2021-02-17 09:21 UTC, SpedNSFW requested changes
This scraper is applicable to some of the other sites on the Puffy Network. Make these changes and rename the file to `PuffyNetworkSite.yml`. Also add the new sites to the SCRAPER-LIST.md file.

2021-02-17 09:21 UTC, SpedNSFW commented on wetandpissy.yml
> +      - wetandpissy.com
```suggestion
      - simplyanal.com
      - weliketosuck.com
      - wetandpissy.com
      - wetandpuffy.com
```

2021-02-17 09:21 UTC, SpedNSFW commented on wetandpissy.yml
> +          fixed: wetandpissy
```suggestion
          selector: //img[@class="logo-overley"]/@src|//ul[@class="nav-list"]/li/a/img/@src
          postProcess:
            - replace:
              - regex: .+?\.(.+?)\..+
                with: $1
```

2021-02-17 09:21 UTC, SpedNSFW commented on wetandpissy.yml
> +          - parseDate: Jan 2, 2006
```suggestion
          - parseDate: Jan 02, 2006
```

2021-02-17 10:58 UTC, SpedNSFW requested changes

2021-02-17 10:58 UTC, SpedNSFW commented on SCRAPERS-LIST.md
> +wetandpissy.com|PuffyNetworkSite.yml|:heavy_check_mark:|:x:|:x:|:x:|-|-
```suggestion
wetandpissy.com|PuffyNetworkSite.yml|:heavy_check_mark:|:x:|:x:|:x:|-|-
wetandpuffy.com|PuffyNetworkSite.yml|:heavy_check_mark:|:x:|:x:|:x:|-|-
```

2021-02-17 11:03 UTC, SpedNSFW requested changes

2021-02-17 11:03 UTC, SpedNSFW commented on scrapers/PuffyNetworkSite.yml
> +name: wetandpissy
Should change this to PuffyNetworkSite too now.
```suggestion
name: PuffyNetworkSite
```

2021-02-17 11:11 UTC, JaseNZC commented
Sorry guys first time and all , got there in the end with a lot of help thank you.

2021-02-17 12:20 UTC, SpedNSFW approved these changes

2021-02-18 08:23 UTC, bnkai commented on scrapers/PuffyNetworkSite.yml
> +          - parseDate: Jan 02, 2006
```suggestion
          - parseDate: Jan 2, 2006
```
`https://www.wetandpuffy.com/videos/jane-toy/`
`https://www.wetandpissy.com/videos/video-nurse-naomi/`
The 0 breaks the parsing for date in most scenes. Was there a case where 0 was needed?

2021-02-18 08:36 UTC, bnkai commented
Also jsut mentioning that the parent site <www.puffynetwork.com> which we have a scraper for already seems to have the dates even for the sites above that dont use them.

2021-02-18 08:37 UTC, bnkai commented on scrapers/PuffyNetworkSite.yml
> +                with: $1
```suggestion
          postProcess:
            - replace:
                - regex: .+?\.(.+?)\..+
                  with: $1
            - map:
                weliketosuck: We Like To Suck
                wetandpuffy: Wet And Puffy
                wetandpissy: Wet And Pissy
                simplyanal: Simply Anal
```
The above change keep the studio names consistent with the parent studio scraper

2021-02-18 10:49 UTC, merged